### PR TITLE
Timer screen and settings menu improvements

### PR DESCRIPTION
**Pull request by M00NJ**
I recently went trough the guidelines off all the m3 design components to learn more about them. The guidelines state, that the position of the FAB should never change. It should always be pinned to the navbar to create muscle memory. I know that you asked Myzel394 to move the example timer under the FAB in #99 to make the UI feel less cramped, so I played around a bit with keypad size, padding etc. to find a solution that doesn't break the guidelines. I sized the keypad buttons down slightly, added more padding and gave the example timers the default button color, to set them apart more from the rest of the UI. I think it looks pretty good now with the timers above the FAB. Also scrolling through the timers is a little more comfortable since the thumb sits a little further up on the screen anyways. I also added a switch in the settings menu to hide the example timers. If the user still feels like the UI is cramped, they can now either switch to the minimal time picker or hide the example timers (or both), so I think these changes will suit everybody. I also added a new "behavior" category and dividers to the settings menu.

Changes:
- slightly decrease keypad button size
- give example timers default button color
- give time string above keypad more muted text color when there is no input
- move example timers above FAB
- make example timer a preference and add switch to settings menu
- add new "behavior" category to settings menu
- add dividers to settings menu

Before:
254009479-eaca898d-f4f8-49c2-a723-d8dc077a44ca

After:
Screenshot_20230803-104317

New settings menu:
Screenshot_20230803-124019

### CODE REVIEW

**Comment by M00NJ** [comment]
I'm not sure where I made a mistake. The App ran perfectly in debugging mode on my phone...

**Comment by Bnyro** [comment]
timer_useTimePicker needs to be renamed to timer_use_time_picker everywhere in the project (you can use Ctrl+shift+r)

**Comment by Bnyro** [comment]
I think it would be a good idea to move the floating action button to the right, and place the quick (preset) timers to the left of them in a column with `Modifier.weight(1f)`.

**Comment by Bnyro** [comment]
Looks good to me otherwise!

**Comment by M00NJ** [comment]
> I think it would be a good idea to move the floating action button to the bottom right, and place the quick (preset) timers to the left of them in a column with `Modifier.weight(1f)`.

I think you might be on to something here. This could look nice and less cramped. It would reduce the the amount of timers on screen to 3 though. The only problem when implementing this would be the secondary FAB that appears when a timer is already running and you add a new one. It would overlap with the timers. We could solve this by having the secondary FAB appear above the primary, but this would get pretty close to the Keypad again. The screenshot shows the secondary FAB, the picture is from the M3 website and shows multiple FABs stacked vertically.


Screenshot_20230805-143949


image

**Comment by Bnyro** [comment]
Having a secondary FAB above the main one sounds like a great idea, that'll probably look awesome!

**Comment by M00NJ** [comment]
I've implemented the column. This is how it looks now. Since there can only be 3 timer on screen at once, I've moved them to the center as much as possible. I also centered the timers vertically inside of the row, I think this looks better than having them pinned to the bottom like the FAB. If you prefer this to the previous screenshot, I will change the position of the secondary FAB next. However there is not much space above the primary FAB, so it will probably move the Keypad up a bit. We could also go for a small secondary FAB, like in the picture from my last comment, to save more space.

Screenshot_20230805-211041

**Comment by M00NJ** [comment]
I've moved the secondary FAB now. Here are to Screenshots, on with small-FAB and one with regular size. Since the icon is the same that's used for the stopwatch tab it might be confusing, so I used a "go back" icon instead (G-Clock uses a trashcan icon, but I don't think that's intuitive). I also used the tertiary color to follow the guidelines. I think this looks very good overall. The only thing is that the Keypad moves up slightly, when the secondary FAB is present, since it's in a column with `Modifier.weight(1f)`. Should I change something about that as well, or do you think it's fine like this?

Screenshot_20230806-103602
Screenshot_20230806-103442

**Comment by Bnyro** [comment]
I think it's fine when we use a smaller, secondary FAB.
Though I'm not sure if the back icon really fits the action to navigate to the other times, I'd rather think it clears the timers because it could be interpreted as a clear button.

**Comment by M00NJ** [comment]
> I think it's fine when we use a smaller, secondary FAB. Though I'm not sure if the back icon really fits the action to navigate to the other times, I'd rather think it clears the timers because it could be interpreted as a clear button.

Small FAB it is then :) I think the arrow represents going back quite well, like in a browser. I don't make the association with a clear action, that would be represented by a trashcan icon or a backspace icon like the one above on the keypad. But what you say goes. If you don't like it, I will change it to the AvTimer icon (There is no fill version though)

**Comment by Bnyro** [comment]
If you think that the icon is self-explaining to users, then that's fine by me!

**Comment by M00NJ** [comment]
> If you think that the icon is self-explaining to users, then that's fine by me! :)

Alright :)
I've pushed the changes now. There was a 13min example timer that I removed, because I don't think 13min is a common timer to set and the space is even more limited now, so more scrolling is needed to get to the long timers. I also applied the tertiary color to the secondary FABs in the stopwatch tab for consistency.

**Review by Bnyro — APPROVED** [review]
Thank you! <3

**Pull request merged**
